In [1]:
import torch
import numpy as np

In [2]:
f1 = torch.tensor([1, 45, 23], dtype=torch.float16)
print(f1)

tensor([ 1., 45., 23.], dtype=torch.float16)


In [3]:
1 + f1

tensor([ 2., 46., 24.], dtype=torch.float16)

In [4]:
1/f1

tensor([1.0000, 0.0222, 0.0435], dtype=torch.float16)

In [5]:
f32 = torch.tensor([1, 45, 23], dtype=torch.float64)
print(f32)

tensor([ 1., 45., 23.], dtype=torch.float64)


In [6]:
1/f32

tensor([1.0000, 0.0222, 0.0435], dtype=torch.float64)

In [7]:
f1 + f32

tensor([ 2., 90., 46.], dtype=torch.float64)

### where tensor are stored

In [8]:
f32.device

device(type='cpu')

In [9]:
f1.device

device(type='cpu')

### some math functions

In [10]:
torch.multiply(f32, 101)

tensor([ 101., 4545., 2323.], dtype=torch.float64)

In [14]:
torch.sum(f32)

tensor(69., dtype=torch.float64)

In [16]:
torch.sum(f32,(0))

tensor(69., dtype=torch.float64)

In [17]:
data = torch.tensor([
                    [1,2,7],
                    [4,5,9]
])

In [18]:
torch.sum(data, 1)

tensor([10, 18])

In [19]:
torch.sum(data)

tensor(28)

In [20]:
torch.sum(data, 0)

tensor([ 5,  7, 16])

In [21]:
torch.sum(data, (0,1))

tensor(28)

In [23]:
torch.sum(data, (-1))

tensor([10, 18])

### element wise mulitplication

In [24]:
f1 * f32

tensor([1.0000e+00, 2.0250e+03, 5.2900e+02], dtype=torch.float64)

In [25]:
f1

tensor([ 1., 45., 23.], dtype=torch.float16)

In [26]:
f32

tensor([ 1., 45., 23.], dtype=torch.float64)

### tranpose

In [27]:
d = torch.tensor(np.arange(1,10).reshape(3,3))
                

In [28]:
d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [29]:
d.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=torch.int32)

In [30]:
d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [33]:
d.transpose(1,0)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=torch.int32)

In [34]:
d.transpose(0,1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=torch.int32)

# 

# 
Neural networks are full of matrix multiplications and dot products.

In [35]:
# y =A.xT+b
A =d

In [36]:
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

### torch.nn.linear

In [39]:
torch.manual_seed(43)

In [40]:
l = torch.nn.Linear(in_features=2, out_features=6)

In [41]:
l

Linear(in_features=2, out_features=6, bias=True)

### mean max, min, sum

In [42]:
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [43]:
torch.sum(A, 0)

tensor([12, 15, 18])

In [45]:
torch.mean(A.type(torch.float16))

tensor(5., dtype=torch.float16)

In [46]:
torch.mean(A.type(torch.float16), 0)

tensor([4., 5., 6.], dtype=torch.float16)

In [47]:
torch.mean(A.type(torch.float16), 1)

tensor([2., 5., 8.], dtype=torch.float16)

In [57]:
large_tensor = torch.arange(100, 1000,10).view(2,5,9)

In [58]:
large_tensor

tensor([[[100, 110, 120, 130, 140, 150, 160, 170, 180],
         [190, 200, 210, 220, 230, 240, 250, 260, 270],
         [280, 290, 300, 310, 320, 330, 340, 350, 360],
         [370, 380, 390, 400, 410, 420, 430, 440, 450],
         [460, 470, 480, 490, 500, 510, 520, 530, 540]],

        [[550, 560, 570, 580, 590, 600, 610, 620, 630],
         [640, 650, 660, 670, 680, 690, 700, 710, 720],
         [730, 740, 750, 760, 770, 780, 790, 800, 810],
         [820, 830, 840, 850, 860, 870, 880, 890, 900],
         [910, 920, 930, 940, 950, 960, 970, 980, 990]]])

In [61]:
torch.sum(large_tensor, (0,1))

tensor([5050, 5150, 5250, 5350, 5450, 5550, 5650, 5750, 5850])

In [62]:
torch.sum(large_tensor, (0,))

tensor([[ 650,  670,  690,  710,  730,  750,  770,  790,  810],
        [ 830,  850,  870,  890,  910,  930,  950,  970,  990],
        [1010, 1030, 1050, 1070, 1090, 1110, 1130, 1150, 1170],
        [1190, 1210, 1230, 1250, 1270, 1290, 1310, 1330, 1350],
        [1370, 1390, 1410, 1430, 1450, 1470, 1490, 1510, 1530]])

In [67]:
torch.sum(large_tensor, (1,0))

tensor([5050, 5150, 5250, 5350, 5450, 5550, 5650, 5750, 5850])