### Python array/ numpy array/ torch tensor

In [1]:
import numpy as np
import torch

In [2]:
# method to print data, type of data object, data element type, and dimensionality
def print_data(data):
    print(data)
    print(type(data))
    if not isinstance(data, list):
        print(data.dtype)
        print(data.ndim)

In [3]:
# python list can have non homogenous data int, float, str, dict or other list etc
py_data = [23, 3, 3434,454]
print_data(py_data)

[23, 3, 3434, 454]
<class 'list'>


In [4]:
# numpy array
np_data = np.array([4343,34,5,2323,4554])
print_data(np_data)

[4343   34    5 2323 4554]
<class 'numpy.ndarray'>
int32
1


In [5]:
# pytorch tensor of dim 1
torch_data = torch.tensor([334,43,34,3,5,3434])
print_data(torch_data)

tensor([ 334,   43,   34,    3,    5, 3434])
<class 'torch.Tensor'>
torch.int64
1


### Random tensors

In [6]:
# generating random tensors 
rand_tensor = torch.rand(11)
print_data(rand_tensor)

tensor([0.8233, 0.2223, 0.5361, 0.2163, 0.0267, 0.2575, 0.5699, 0.7694, 0.1790,
        0.0492, 0.3223])
<class 'torch.Tensor'>
torch.float32
1


In [7]:
# Generating tensors from mnumpy array

In [8]:
# generating  tensors from np range
rand_tensor = torch.tensor(np.arange(10).reshape(2,5))
print_data(rand_tensor)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
2


### View function convert to different shape

In [9]:
# Returns a new tensor with the same data as the self tensor but of a different shape.
rand_tensor = torch.rand(20)
view_5_4 = rand_tensor.view(5,4)
print_data(view_5_4)

tensor([[0.9650, 0.8199, 0.2101, 0.3873],
        [0.9322, 0.6945, 0.2381, 0.8166],
        [0.4215, 0.5498, 0.8708, 0.8777],
        [0.5717, 0.8036, 0.2944, 0.5749],
        [0.4887, 0.4623, 0.8998, 0.1735]])
<class 'torch.Tensor'>
torch.float32
2


In [10]:
# use value view 
print_data(view_5_4.view(-1, 1))

tensor([[0.9650],
        [0.8199],
        [0.2101],
        [0.3873],
        [0.9322],
        [0.6945],
        [0.2381],
        [0.8166],
        [0.4215],
        [0.5498],
        [0.8708],
        [0.8777],
        [0.5717],
        [0.8036],
        [0.2944],
        [0.5749],
        [0.4887],
        [0.4623],
        [0.8998],
        [0.1735]])
<class 'torch.Tensor'>
torch.float32
2


### Scaler

In [11]:
# Scaler has ndim 0
s = torch.tensor(1010123)
print_data(s)

tensor(1010123)
<class 'torch.Tensor'>
torch.int64
0


In [12]:
# Get value. 
s.item()

1010123

In [13]:
#  ndim 1
s = torch.tensor([1010123])
print_data(s)
# Get value. 
s.item()

tensor([1010123])
<class 'torch.Tensor'>
torch.int64
1


1010123

In [14]:
# item() do not work with 2 values
#  ndim 1
s = torch.tensor([1010123, 2323])
print_data(s)
# Get value. See by uncommenting following
# s.item()

tensor([1010123,    2323])
<class 'torch.Tensor'>
torch.int64
1


### Matix

In [15]:
# Matrix
matrix = torch.tensor([[237, 28], 
                       [92, 1120]])
matrix

tensor([[ 237,   28],
        [  92, 1120]])

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
matrix.ndim

2

In [18]:
matrix.dtype

torch.int64

In [19]:
matrix.size()

torch.Size([2, 2])

In [20]:
matrix_1_by_4 = matrix.view(4,1)

In [21]:
matrix_1_by_4.size()

torch.Size([4, 1])

In [22]:
matrix_1_by_4

tensor([[ 237],
        [  28],
        [  92],
        [1120]])

In [23]:
# Let sum original matrix

In [24]:
matrix

tensor([[ 237,   28],
        [  92, 1120]])

In [25]:
sum(matrix)

tensor([ 329, 1148])

In [26]:
# By default sum is by flattening array

In [27]:
torch.sum(matrix)

tensor(1477)

In [28]:
# By default sum is by flattening array

In [29]:
torch.sum(matrix, axis=0)

tensor([ 329, 1148])

In [30]:
torch.sum(matrix, axis=1)

tensor([ 265, 1212])